### ISSUE TITLE
Complete list of hardware to build?

### ISSUE THREAD

**Issue by mathrocker666** [johnlamb/LambBT#1]
Hey,

This keeb looks fantastic and I'd like to build one but I have a question: what exactly is needed to build it? M2 standoffs etc?

Thanks

**Comment by johnlamb** [comment]
Thanks!
BOM:
2 pcbs, one for each side
2 MCUs, I am running Nice Nano v2
Legs and sockets for MCU socketing (https://docs.splitkb.com/hc/en-us/articles/360011263059-How-do-I-socket-a-microcontroller-)
2 batteries, I use 301230 3.7V 110mAh batteries that fits under the MCU when socketed.
34 hot swap sockets for Choc v1 switches
34 Choc v1 switches
34 choc v1 key caps
1 PCM12 surface mounted on/off switch
1 B3u1000 button for reset

Case:
3D print on left and one from the stl-files in the repo.
4 M2 threaded inserts
4 M2 screws, 4-5 mm long.
